package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"vehicle-log-graphql-api/common/graphql/graph"
	"vehicle-log-graphql-api/common/graphql/graph/model"
)

// GetAllTown is the resolver for the GetAllTown field.
func (r *queryResolver) GetAllTown(ctx context.Context) ([]*model.Town, error) {
	return r.TownHandler.GetaAllTown(ctx)
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
