package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"vehicle-log-graphql-api/common/graphql/graph/model"
)

// GetAllTypes is the resolver for the GetAllTypes field.
func (r *queryResolver) GetAllTypes(ctx context.Context) ([]*model.Types, error) {
	return r.TypeHandler.GetAllTypes(ctx)
}
