// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FilterReportLogged struct {
	Date     *string `json:"Date,omitempty"`
	TownCode string  `json:"TownCode"`
}

type FilterVehicleTown struct {
	PlatNumber  *string `json:"PlatNumber,omitempty"`
	VehicleType *string `json:"VehicleType,omitempty"`
	TownCode    string  `json:"TownCode"`
}

type LogInRequest struct {
	PlatNumber  string `json:"PlatNumber"`
	TownCode    string `json:"TownCode"`
	VehicleType string `json:"VehicleType"`
}

type LogOutRequest struct {
	PlatNumber  string  `json:"PlatNumber"`
	TownCode    string  `json:"TownCode"`
	VehicleType *string `json:"VehicleType,omitempty"`
}

type LogOutResponse struct {
	TownName    string  `json:"TownName"`
	TotalTime   *int    `json:"TotalTime,omitempty"`
	TimeIn      *string `json:"TimeIn,omitempty"`
	TimeOut     *string `json:"TimeOut,omitempty"`
	DateAt      *string `json:"DateAt,omitempty"`
	PlatNumber  *string `json:"PlatNumber,omitempty"`
	VehicleType *string `json:"VehicleType,omitempty"`
	DateOutAt   *string `json:"DateOutAt,omitempty"`
	TownCode    *string `json:"TownCode,omitempty"`
}

type Town struct {
	ID       *string `json:"Id,omitempty"`
	TownCode *string `json:"TownCode,omitempty"`
	TownName *string `json:"TownName,omitempty"`
}

type TownLogReport struct {
	TownCode    *string `json:"TownCode,omitempty"`
	VehicleType *string `json:"VehicleType,omitempty"`
	TotalLogged *int    `json:"TotalLogged,omitempty"`
	Quantity    *int    `json:"Quantity,omitempty"`
}

type Types struct {
	ID       *string `json:"Id,omitempty"`
	TypeName *string `json:"TypeName,omitempty"`
}

type VehicleTown struct {
	ID           *string `json:"ID,omitempty"`
	PlatNumber   *string `json:"PlatNumber,omitempty"`
	VehicleType  *string `json:"VehicleType,omitempty"`
	TimeCheckIn  *string `json:"TimeCheckIn,omitempty"`
	TimeCheckOut *string `json:"TimeCheckOut,omitempty"`
	DateCheckIn  *string `json:"DateCheckIn,omitempty"`
	DateCheckOut *string `json:"DateCheckOut,omitempty"`
}
